<a href="https://colab.research.google.com/github/BishalMondal/Crop-Disease-Detection/blob/main/ResNet50.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from keras.preprocessing.image import ImageDataGenerator
import keras
from keras.models import Sequential
from keras.layers import Input, Dense
from tensorflow.keras.applications import ResNet50,ResNet50V2,InceptionResNetV2
from tensorflow.keras.applications.resnet50 import preprocess_input
print(keras.__version__)

2.7.0


In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
num_classes = 61

image_resize = 224

batch_size_training = 64
batch_size_validation = 32

In [5]:
data_generator = ImageDataGenerator(
    preprocessing_function=preprocess_input,
)

In [6]:
train_generator = data_generator.flow_from_directory(
    "/content/drive/MyDrive/training-data",
    target_size=(image_resize, image_resize),
    batch_size=batch_size_training,
    class_mode='categorical')

Found 31751 images belonging to 61 classes.


In [7]:
validation_generator = data_generator.flow_from_directory(
    '/content/drive/MyDrive/validation-data',
    target_size=(image_resize, image_resize),
    batch_size=batch_size_validation,
    class_mode='categorical')

Found 4546 images belonging to 60 classes.


In [8]:
model = Sequential()

In [9]:
model.add(ResNet50(
    include_top=False,
    pooling='avg',
    weights='imagenet',
    ))

94781440/94765736 [==============================] - 1s 0us/step


In [10]:
model.add(Dense(num_classes, activation='softmax'))

In [11]:
model.layers[0].trainable = False

In [12]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [13]:
steps_per_epoch_training = 16
steps_per_epoch_validation = 14
num_epochs = 10

In [15]:
from PIL import ImageFile
ImageFile.LOAD_TRUNCATED_IMAGES = True

fit_history = model.fit_generator(
    train_generator,
    steps_per_epoch=16,
    epochs=10,
    #validation_data=validation_generator,
    #validation_steps=14,
)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  import sys


Epoch 1/10
16/16 [==============================] - 204s 12s/step - loss: 0.6697 - accuracy: 0.7734
Epoch 2/10
16/16 [==============================] - 193s 11s/step - loss: 0.6230 - accuracy: 0.7852
Epoch 3/10
16/16 [==============================] - 193s 11s/step - loss: 0.6152 - accuracy: 0.7910
Epoch 4/10
16/16 [==============================] - 186s 11s/step - loss: 0.5427 - accuracy: 0.8105
Epoch 5/10
16/16 [==============================] - 182s 11s/step - loss: 0.5274 - accuracy: 0.8174
Epoch 6/10
16/16 [==============================] - 181s 11s/step - loss: 0.4844 - accuracy: 0.8369
Epoch 7/10
16/16 [==============================] - 181s 11s/step - loss: 0.5189 - accuracy: 0.8252
Epoch 8/10
16/16 [==============================] - 180s 11s/step - loss: 0.5164 - accuracy: 0.8262
Epoch 9/10
16/16 [==============================] - 177s 11s/step - loss: 0.4824 - accuracy: 0.8311
Epoch 10/10
16/16 [==============================] - 178s 10s/step - loss: 0.4613 - accuracy: 0.8389

In [16]:
count = 0
while count < 10:
  print("Step: ", count)
  fit_history = model.fit_generator(
    train_generator,
    steps_per_epoch=16,
    epochs=10,
    #validation_data=validation_generator,
    #validation_steps=14,
  )
  count += 1

Step:  0


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  import sys


Epoch 1/10
16/16 [==============================] - 175s 11s/step - loss: 0.5218 - accuracy: 0.8096
Epoch 2/10
16/16 [==============================] - 177s 11s/step - loss: 0.5135 - accuracy: 0.8193
Epoch 3/10
16/16 [==============================] - 179s 11s/step - loss: 0.4737 - accuracy: 0.8262
Epoch 4/10
16/16 [==============================] - 178s 11s/step - loss: 0.4758 - accuracy: 0.8154
Epoch 5/10
16/16 [==============================] - 175s 11s/step - loss: 0.4732 - accuracy: 0.8330
Epoch 6/10
16/16 [==============================] - 172s 10s/step - loss: 0.4232 - accuracy: 0.8311
Epoch 7/10
16/16 [==============================] - 177s 11s/step - loss: 0.4703 - accuracy: 0.8223
Epoch 8/10
16/16 [==============================] - 171s 10s/step - loss: 0.4483 - accuracy: 0.8369
Epoch 9/10
16/16 [==============================] - 174s 10s/step - loss: 0.4075 - accuracy: 0.8613
Epoch 10/10
16/16 [==============================] - 170s 10s/step - loss: 0.4028 - accuracy: 0.8447

In [34]:
test_data_generator = data_generator.flow_from_directory(
    '/content/drive/MyDrive/validation-data',
    target_size=(image_resize, image_resize),
    batch_size=batch_size_validation,
    shuffle = 'False',
    class_mode='categorical'
)

Found 4546 images belonging to 60 classes.


In [35]:
fit_history.history.get('accuracy')[-1]

0.890625

In [36]:
training_loss_resnet = fit_history.history['loss'][-1]
training_loss_resnet

0.2776842713356018

In [37]:
predicted_values = model.predict(test_data_generator)

In [38]:
import numpy as np
y_pred_res = np.argmax(predicted_values, axis=1)

In [39]:
from sklearn.metrics import classification_report, confusion_matrix
print('Confusion Matrix')
conf_matrix_res = confusion_matrix(test_data_generator.classes, y_pred_res)
cm_res = np.array2string(conf_matrix_res)
print(conf_matrix_res)

Confusion Matrix
[[10  1  2 ...  0  0  3]
 [ 0  0  0 ...  0  0  0]
 [ 1  0  0 ...  0  0  0]
 ...
 [ 1  0  0 ...  0  0  0]
 [ 2  0  2 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]


In [40]:
target_names = []
count = 0
while count < 61:
  target_names.append(str(count))
  count += 1

print(target_names)

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46', '47', '48', '49', '50', '51', '52', '53', '54', '55', '56', '57', '58', '59', '60']


In [41]:
print('Classification Report')
class_rep_res = classification_report(test_data_generator.classes, y_pred_res, target_names=target_names)

print(class_rep_res)

Classification Report
              precision    recall  f1-score   support

           0       0.06      0.06      0.06       169
           1       0.00      0.00      0.00        30
           2       0.00      0.00      0.00        27
           3       0.00      0.00      0.00        24
           4       0.00      0.00      0.00        69
           5       0.00      0.00      0.00        51
           6       0.00      0.00      0.00        29
           7       0.02      0.03      0.02        71
           8       0.03      0.03      0.03       116
           9       0.00      0.00      0.00        42
          10       0.00      0.00      0.00        54
          11       0.02      0.02      0.02        66
          12       0.00      0.00      0.00        22
          13       0.00      0.00      0.00        74
          14       0.01      0.02      0.01        59
          15       0.00      0.00      0.00         9
          16       0.02      0.02      0.02        90
     

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1